version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '256M'

  sensor1:
    build:
      context: ./sensors_container
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - SENSOR_ID=sensor1
      - CAR_ID=carro1
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128M'

  sensor2:
    build:
      context: ./sensors_container
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - SENSOR_ID=sensor2
      - CAR_ID=carro2
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128M'

  sensor3:
    build:
      context: ./sensors_container
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - SENSOR_ID=sensor3
      - CAR_ID=carro3
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128M'

  telegram_bot:
    build:
      context: ./telegram_bot_container
    container_name: telegram_bot_container
    environment:
      - TELEGRAM_BOT_TOKEN=7693586888:AAERrtk5fZZ2FkdRwFQK6-ovbNiNeZUrUic
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '128M'

  processing:
    build:
      context: ./processing_container
    container_name: processing_container
    depends_on:
      - mqtt
      - telegram_bot
    ports:
      - "5000:5000"
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '256M'