version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log

  sensors:
    build:
      context: ./sensors_container
    container_name: sensors_container
    depends_on:
      - mqtt
    restart: always

  processing:
    build:
      context: ./processing_container
    container_name: processing_container
    depends_on:
      - mqtt
    restart: always