version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log

  sensors:
    build:
      context: ./sensors_container
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
      - CAR_ID=carro${SENSOR_ID}
    deploy:
      replicas: 1
    restart: always

  telegram_bot:
    build:
      context: ./telegram_bot_container
    container_name: telegram_bot_container
    environment:
      - TELEGRAM_BOT_TOKEN=7693586888:AAERrtk5fZZ2FkdRwFQK6-ovbNiNeZUrUic
    restart: always

  processing:
    build:
      context: ./processing_container
    container_name: processing_container
    depends_on:
      - mqtt
      - telegram_bot
    ports:
      - "5000:5000"
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_PORT=1883
    restart: always