apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
    spec:
      containers:
      - name: data-collector
        image: data-collector:latest
        env:
          - name: MQTT_BROKER_HOST
            value: "mqtt-broker"  # Nome do serviço do broker MQTT
          - name: MQTT_BROKER_PORT
            value: "1883"
